import { Officer } from "@/types/officer";

export const MOCK_OFFICERS: Officer[] = [
  // Kolhapur Division Officers (KMC)
  {
    id: "off-1",
    badgeId: "OFF-WM-101",
    name: "R. K. Patil",
    designation: "Senior Sanitary Inspector",
    department: "Solid Waste Management",
    departmentId: "dept-kmc-waste",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 98221 44550",
    email: "rk.patil@kmc.gov.in",
    status: "ON_DUTY",
    assignedComplaintsCount: 4,
    resolvedComplaintsCount: 88,
    performanceScore: 96,
    averageResolutionHours: 3.5,
    assignedZone: "North Zone",
  },
  {
    id: "off-2",
    badgeId: "OFF-HY-202",
    name: "Sunil Deshmukh",
    designation: "Executive Hydraulic Engineer",
    department: "Hydraulics & Water Supply",
    departmentId: "dept-kmc-water",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 98223 11445",
    email: "sunil.deshmukh@kmc.gov.in",
    status: "BUSY",
    assignedComplaintsCount: 6,
    resolvedComplaintsCount: 112,
    performanceScore: 92,
    averageResolutionHours: 4.8,
    assignedZone: "Central Zone",
  },
  {
    id: "off-3",
    badgeId: "OFF-PW-303",
    name: "Anand Shinde",
    designation: "Assistant PWD Road Supervisor",
    department: "Roads & Traffic Infrastructure (PWD)",
    departmentId: "dept-kmc-pwd",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 97654 32100",
    email: "anand.shinde@kmc.gov.in",
    status: "AVAILABLE",
    assignedComplaintsCount: 2,
    resolvedComplaintsCount: 74,
    performanceScore: 89,
    averageResolutionHours: 8.2,
    assignedZone: "Central Zone",
  },
  {
    id: "off-4",
    badgeId: "OFF-SN-404",
    name: "Pooja Jadhav",
    designation: "Drainage & Sewerage Inspector",
    department: "Sanitation & Stormwater Drainage",
    departmentId: "dept-kmc-drainage",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 98112 33445",
    email: "pooja.jadhav@kmc.gov.in",
    status: "AVAILABLE",
    assignedComplaintsCount: 1,
    resolvedComplaintsCount: 95,
    performanceScore: 97,
    averageResolutionHours: 2.9,
    assignedZone: "South Zone",
  },
  {
    id: "off-5",
    badgeId: "OFF-EL-505",
    name: "Vikram Gaikwad",
    designation: "Electrical Line Supervisor",
    department: "Electrical & Street Lighting",
    departmentId: "dept-kmc-electric",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 99881 22334",
    email: "vikram.gaikwad@kmc.gov.in",
    status: "ON_DUTY",
    assignedComplaintsCount: 3,
    resolvedComplaintsCount: 140,
    performanceScore: 94,
    averageResolutionHours: 4.1,
    assignedZone: "East Zone",
  },
  {
    id: "off-6",
    badgeId: "OFF-WM-106",
    name: "Suresh Bhosale",
    designation: "Field Sanitation Officer",
    department: "Solid Waste Management",
    departmentId: "dept-kmc-waste",
    authorityId: "auth-kmc",
    authorityName: "Kolhapur Municipal Corporation (KMC)",
    districtId: "dist-kolhapur",
    divisionId: "div-kolhapur",
    divisionName: "Kolhapur Division",
    mobileNumber: "+91 98901 22334",
    email: "suresh.bhosale@kmc.gov.in",
    status: "OFF_DUTY",
    assignedComplaintsCount: 0,
    resolvedComplaintsCount: 65,
    performanceScore: 90,
    averageResolutionHours: 5.5,
    assignedZone: "North Zone",
  },

  // Pune Division Officers (PMC)
  {
    id: "off-7",
    badgeId: "OFF-PMC-107",
    name: "Kunal Tambe",
    designation: "Zonal Sanitation Officer",
    department: "Solid Waste & Bio-Sanitation",
    departmentId: "dept-pmc-waste",
    authorityId: "auth-pmc",
    authorityName: "Pune Municipal Corporation (PMC)",
    districtId: "dist-pune",
    divisionId: "div-pune",
    divisionName: "Pune Division",
    mobileNumber: "+91 98230 55667",
    email: "kunal.tambe@punecorporation.org",
    status: "AVAILABLE",
    assignedComplaintsCount: 3,
    resolvedComplaintsCount: 160,
    performanceScore: 95,
    averageResolutionHours: 3.2,
    assignedZone: "Kothrud Ward",
  },
  {
    id: "off-8",
    badgeId: "OFF-PMC-108",
    name: "Aditi Rao",
    designation: "Hydraulic Maintenance Engineer",
    department: "Water Infrastructure & Pipelines",
    departmentId: "dept-pmc-water",
    authorityId: "auth-pmc",
    authorityName: "Pune Municipal Corporation (PMC)",
    districtId: "dist-pune",
    divisionId: "div-pune",
    divisionName: "Pune Division",
    mobileNumber: "+91 98224 88990",
    email: "aditi.rao@punecorporation.org",
    status: "ON_DUTY",
    assignedComplaintsCount: 5,
    resolvedComplaintsCount: 135,
    performanceScore: 93,
    averageResolutionHours: 4.0,
    assignedZone: "Shivajinagar Ward",
  },
];

export async function getOfficers(jurisdiction?: {
  divisionId?: string;
  authorityId?: string;
  departmentId?: string;
}): Promise<Officer[]> {
  let list = [...MOCK_OFFICERS];
  if (jurisdiction?.divisionId) {
    list = list.filter((o) => o.divisionId === jurisdiction.divisionId);
  }
  if (jurisdiction?.authorityId) {
    list = list.filter((o) => o.authorityId === jurisdiction.authorityId);
  }
  if (jurisdiction?.departmentId) {
    list = list.filter((o) => o.departmentId === jurisdiction.departmentId);
  }
  return list;
}

export async function getOfficerById(id: string): Promise<Officer | undefined> {
  return MOCK_OFFICERS.find((o) => o.id === id);
}
